export const BRANCH_LIST_REQUEST = 'BRANCH_LIST_REQUEST';
export const BRANCH_LIST_SUCCESS = 'BRANCH_LIST_SUCCESS';
export const BRANCH_LIST_FAIL = 'BRANCH_LIST_FAIL';

export const BRANCH_DETAILS_REQUEST = 'BRANCH_DETAILS_REQUEST';
export const BRANCH_DETAILS_SUCCESS = 'BRANCH_DETAILS_SUCCESS';
export const BRANCH_DETAILS_FAIL = 'BRANCH_DETAILS_FAIL';

export const BRANCH_SAVE_REQUEST = 'BRANCH_SAVE_REQUEST';
export const BRANCH_SAVE_SUCCESS = 'BRANCH_SAVE_SUCCESS';
export const BRANCH_SAVE_FAIL = 'BRANCH_SAVE_FAIL';

export const BRANCH_DELETE_REQUEST = 'BRANCH_DELETE_REQUEST';
export const BRANCH_DELETE_SUCCESS = 'BRANCH_DELETE_SUCCESS';
export const BRANCH_DELETE_FAIL = 'BRANCH_DELETE_FAIL';