export const PLAN_LIST_REQUEST = 'PLAN_LIST_REQUEST';
export const PLAN_LIST_SUCCESS = 'PLAN_LIST_SUCCESS';
export const PLAN_LIST_FAIL = 'PLAN_LIST_FAIL';

export const PLAN_ACTIVE_REQUEST = 'PLAN_ACTIVE_REQUEST';
export const PLAN_ACTIVE_SUCCESS = 'PLAN_ACTIVE_SUCCESS';
export const PLAN_ACTIVE_FAIL = 'PLAN_ACTIVE_FAIL';

export const PLAN_DETAILS_REQUEST = 'PLAN_DETAILS_REQUEST';
export const PLAN_DETAILS_SUCCESS = 'PLAN_DETAILS_SUCCESS';
export const PLAN_DETAILS_FAIL = 'PLAN_DETAILS_FAIL';

export const PLAN_SAVE_REQUEST = 'PLAN_SAVE_REQUEST';
export const PLAN_SAVE_SUCCESS = 'PLAN_SAVE_SUCCESS';
export const PLAN_SAVE_FAIL = 'PLAN_SAVE_FAIL';

export const PLAN_DELETE_REQUEST = 'PLAN_DELETE_REQUEST';
export const PLAN_DELETE_SUCCESS = 'PLAN_DELETE_SUCCESS';
export const PLAN_DELETE_FAIL = 'PLAN_DELETE_FAIL';